[package]
name = "advent-of-code"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"